i#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here
module load samtools/1.19 bowtie2 boost tophat
tophat -r 200 -G /project/bf528/project_2/reference/annot/mm9.gtf --segment-length=20 --segment-mismatches=1 --no-novel-juncs -o P0_1_tophat -p 16 /projectnb/bf528/users/wheeler/project_5/Jessica/mm9.fa P0_1_1.fastq P0_1_2.fastq
echo "Job finished: $(date +%F)"

